const { DATABASE_CLOUD, PORT, NODE_ENV, JWT_SECRET, CLOUDINARY_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET_KEY, CLOUDINARY_URL, NODE_MAILER_PASS, NODE_MAILER_USER, VERIFICATION_EMAIL, FORNTEND_URL, SIGN_IN_URL, CRYPTR_KEY } = process.env;

module.exports = {
  DATABASE_CLOUD,
  PORT,
  NODE_ENV,
  JWT_SECRET,
  CLOUDINARY_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET_KEY,
  CLOUDINARY_URL,
  NODE_MAILER_PASS,
  NODE_MAILER_USER,
  VERIFICATION_EMAIL,
  FORNTEND_URL,
  SIGN_IN_URL,
  CRYPTR_KEY,
};
